delete

diff --git a/express-gen/gen b/express-gen/gen
--- a/express-gen/gen
+++ b/express-gen/gen
@@ -7,6 +7,14 @@ help() {
 	echo
 }
 
+check_dependencies() {
+	which npm;
+	if [ $? != 0 ]; then
+		echo "ERROR need npm package"
+		echo "see nodejs/install.sh"
+	fi
+}
+
 check_folder() {
 	if [ "$1" == ""	]; then
 		echo "ERROR: folder can not be empty"
@@ -26,6 +34,7 @@ check_domain() {
 	fi
 }
 
+
 if [ $# != 2 ]; then
 	help
 	exit 0
@@ -34,6 +43,7 @@ fi
 proj_name=$1
 proj_domain=$2
 
+check_dependencies
 check_folder $proj_name
 check_domain $proj_domain
 
@@ -42,7 +52,7 @@ mkdir $proj_name
 
 if [ $? != 0 ]; then
 	echo "ERROR: can not create folder $proj_name"
-	exit 3
+	exit 1
 fi
 
 cd $proj_name
@@ -52,6 +62,12 @@ echo [==ENSURE INSTALL EXPRESS==]
 which express
 if [ $? != 0 ]; then 
 	npm install -g express
+	if [ $? != 0 ]; then
+		echo ERROR: npm not found or network problem?
+		cd ..
+		rm -rf $proj_name
+		exit 1
+	fi
 fi
 
 echo [==GENERATE CODE==]
